### ISSUE TITLE
genini can't find ${pkg_name[${n}]}-${PVR}.hint

### ISSUE THREAD

**Issue by fd00** [cygwinports/cygport#1]
(Sorry, I'm not good at English.)

`setup.hint` is renamed to `${pkg_name[${n}]}-${PVR}.hint` by patch https://github.com/cygwinports/cygport/commit/fb07f529789a787d1ef15f0ea2d2e8bbdb0f3c75

Therefore cygwin genini can't find hint file to create setup.ini.

* https://cygwin.com/git/?p=cygwin-apps/genini.git;a=blob;f=genini;h=33b46fe855d3a1708302ffee365453d6f360bd68;hb=HEAD#l205

Do you have any idea to fix it?
Or could you tell me a workaround?

**Comment by jon-turney** [comment]
This could be fixed in genini, but as workarounds, you could
- use mksetupini from the calm package, instead of genini
- rename the file back to setup.hint

**Comment by fd00** [comment]
I installed calm and mksetupini generated setup.ini successfully.
Thank you.
